import { MarketConfig } from './types';

export const NZ_MARKET: MarketConfig = {
  id: 'nz',
  displayName: 'New Zealand',
  country: 'New Zealand',
  currency: 'NZD',
  currencySymbol: '$',
  locale: 'en-NZ',

  funderTypeHints: [
    'Local and city councils, district and regional authorities — list EVERY individual council by its full official name',
    'National government ministries, departments, and statutory grant-making agencies',
    'Government-funded agencies and Crown entities with community grant programmes',
    'International government and multilateral bodies (UN agencies, EU funds, World Bank NGO windows, USAID, bilateral foreign aid)',
    'National lottery distributors and gaming/TAB-related community trust grant programmes',
    'Community foundations and regional endowment funds (pooled local philanthropy)',
    'Private and family philanthropic foundations',
    'Corporate foundations (philanthropic arms of major companies)',
    'Charitable trusts with specific mandated purposes (health, education, environment, sport, arts, housing, etc.)',
    'Corporate CSR and community investment programmes (non-foundation, direct company giving)',
    'Industry associations and trade bodies with community or social good grant funds',
    'Faith-based, church, and religious denominational charitable funds and community trusts',
    'Federated and workplace giving programmes that distribute pooled donations as grants (e.g. United Way)',
    'Ethnic, cultural, and diaspora community associations with grant programmes',
    'Neighbourhood, community development, and resident association small grants',
    'Large international NGOs and development organisations that sub-grant to local nonprofits (e.g. Oxfam, CARE, Save the Children)',
    'Global thematic funds with NGO grant windows (Global Fund, Green Climate Fund, food security, global health funds)',
    'University and research institution community partnership grants (where nonprofits can be lead or co-applicant)',
    'Social enterprise support programmes, accelerators, and incubators with non-returnable grant components',
  ],

  funderTypeGroups: [
    // Group 1: Local Councils — own call; NZ has 78 territorial authorities, needs full token budget
    [
      'Local and city councils, district and regional authorities — list EVERY individual council by its full official name',
    ],
    // Group 2: Government & Lottery
    [
      'National government ministries, departments, and statutory grant-making agencies',
      'Government-funded agencies and Crown entities with community grant programmes',
      'National lottery distributors and gaming/TAB-related community trust grant programmes',
    ],
    // Group 3: Foundations & Trusts
    [
      'Community foundations and regional endowment funds (pooled local philanthropy)',
      'Private and family philanthropic foundations',
      'Corporate foundations (philanthropic arms of major companies)',
      'Charitable trusts with specific mandated purposes (health, education, environment, sport, arts, housing, etc.)',
    ],
    // Group 4: Corporate & Industry
    [
      'Corporate CSR and community investment programmes (non-foundation, direct company giving)',
      'Industry associations and trade bodies with community or social good grant funds',
      'Faith-based, church, and religious denominational charitable funds and community trusts',
    ],
    // Group 5: Community & Cultural
    [
      'Federated and workplace giving programmes that distribute pooled donations as grants (e.g. United Way)',
      'Ethnic, cultural, and diaspora community associations with grant programmes',
      'Neighbourhood, community development, and resident association small grants',
    ],
    // Group 6: International
    [
      'International government and multilateral bodies (UN agencies, EU funds, World Bank NGO windows, USAID, bilateral foreign aid, MFAT Pacific partnerships)',
      'Large international NGOs and development organisations that sub-grant to local nonprofits (e.g. Oxfam, CARE, Save the Children)',
      'Global thematic funds with NGO grant windows (Global Fund, Green Climate Fund, food security, global health funds)',
    ],
    // Group 7: Research & Social Enterprise
    [
      'University and research institution community partnership grants (where nonprofits can be lead or co-applicant)',
      'Social enterprise support programmes, accelerators, and incubators with non-returnable grant components',
    ],
  ],

  grantDirectories: [
    'https://www.fundinginformation.org.nz',
    'https://www.communitymatters.govt.nz/our-funding',
    'https://generosity.org.nz/giv-us',
    'https://www.philanthropy.org.nz/fundseeker',
    'https://www.philanthropy.org.nz/our-members',
    'https://community.net.nz/',
    'https://www.perpetualguardian.co.nz/philanthropy/grant-seekers/grants-open-upcoming/',
    'https://www.publictrust.co.nz/grants/',
    'https://www.doc.govt.nz/get-involved/funding/other-funding-organisations/',
    'https://sportnz.org.nz/get-into-sport/search-for-funding/search',
    'https://tindall.org.nz/other-funding-resources/',
    'https://www.business.govt.nz/tax-and-money/getting-government-grants',
  ],

  curatedFunderUrls: [
    // ── Government grant programs — national ────────────────────────────────
    { url: 'https://www.communitymatters.govt.nz/community-organisations-grants-scheme' },
    { url: 'https://www.communitymatters.govt.nz/lottery-grants-board' },
    { url: 'https://www.communitymatters.govt.nz/lottery-community' },
    { url: 'https://www.communitymatters.govt.nz/lottery-environment-and-heritage' },
    { url: 'https://www.communitymatters.govt.nz/lottery-community-facilities' },
    { url: 'https://www.communitymatters.govt.nz/lottery-individuals-with-disabilities' },
    { url: 'https://www.communitymatters.govt.nz/lottery-significant-projects-fund' },
    { url: 'https://www.communitymatters.govt.nz/lottery-outdoor-safety' },
    { url: 'https://www.communitymatters.govt.nz/lottery-health-research' },
    { url: 'https://www.communitymatters.govt.nz/lottery-ministers-discretionary-fund' },
    { url: 'https://www.communitymatters.govt.nz/pacific-development-and-conservation-trust-2' },
    { url: 'https://www.dia.govt.nz/Services-Community-Funding-Significant-Community-Based-Projects-Fund' },
    { url: 'https://creativenz.govt.nz/funding-and-support/all-opportunities' },
    { url: 'https://creativenz.govt.nz/funding-and-support/all-opportunities/creative-communities-scheme' },
    { url: 'https://sportnz.org.nz/funding/sport-nz-programmes-and-funding/' },
    { url: 'https://sportnz.org.nz/funding/sport-nz-programmes-and-funding/tu-manawa-active-aotearoa/' },
    { url: 'https://www.doc.govt.nz/get-involved/funding/doc-community-fund/' },
    { url: 'https://environment.govt.nz/what-you-can-do/funding/' },
    { url: 'https://environment.govt.nz/what-you-can-do/funding/community-environment-fund/' },
    { url: 'https://www.msd.govt.nz/what-we-can-do/community/community-capability-and-resilience-fund/index.html' },
    { url: 'https://www.tpk.govt.nz/en/nga-putea-me-nga-ratonga' },
    { url: 'https://www.mch.govt.nz/our-work/apply-funding' },
    { url: 'https://www.mpp.govt.nz/funding/' },
    { url: 'https://www.nzonair.govt.nz/funding/' },
    { url: 'https://www.heritage.org.nz/resources/funding' },
    { url: 'https://www.nzta.govt.nz/safety/what-waka-kotahi-is-doing/community-road-safety-fund/' },
    { url: 'https://www.civildefence.govt.nz/cdem-sector/cdem-resilience-fund' },
    { url: 'https://www.myd.govt.nz/funding' },
    { url: 'https://www.eeca.govt.nz/co-funding-and-support/products/community-renewable-energy-fund/' },
    { url: 'https://www.hrc.govt.nz/grants-funding' },
    { url: 'https://www.tec.govt.nz/funding/funding-and-performance/funding/fund-finder/ace/ace-in-communities' },
    { url: 'https://www.nzfilm.co.nz/funding-support-nz-filmmakers/funding' },
    // ── Gaming trusts — national ────────────────────────────────────────────
    { url: 'https://www.nzct.org.nz/grants/' },
    { url: 'https://lionfoundation.nz/apply-for-funding/' },
    { url: 'https://www.pelorustrust.net.nz/process-for-funding' },
    // The Southern Trust (tst.org.nz) = AGT (agt.nz) — same entity, listed below
    { url: 'https://www.fourwindsfoundation.co.nz/community/community-gaming/' },
    { url: 'https://www.pubcharitylimited.org.nz/grants' },
    { url: 'https://www.trillian.co.nz/grants/' },
    { url: 'https://onefoundation.nz/grants' },
    { url: 'https://www.agt.nz/funding/applying-for-funding' },
    { url: 'https://www.grassrootstrust.co.nz/apply-for-a-grant/' },
    { url: 'https://mainlandfoundation.co.nz/grant-funding/' },
    { url: 'https://bluesky.org.nz/grants/grants.html' },
    { url: 'https://www.dragon.org.nz/grants' },
    { url: 'https://www.firstlightfoundation.co.nz/grants.html', regions: ['hawkes-bay', 'bay-of-plenty'] },
    { url: 'https://www.youthtown.org.nz/funding/', regions: ['auckland'] },
    { url: 'https://www.thetrusts.co.nz/community/grants/', regions: ['auckland'] },
    { url: 'https://infinityfoundation.co.nz/apply-for-a-grant/' },
    { url: 'https://www.ilt.co.nz/ilt-foundation/', regions: ['southland'] },
    { url: 'https://trustaoraki.co.nz/grants/', regions: ['canterbury'] },
    { url: 'https://www.constellationtrust.co.nz/', regions: ['auckland'] },
    { url: 'https://www.redwoodtrust.org.nz/apply/', regions: ['waikato'] },
    { url: 'https://www.northandsouthtrust.org.nz/grants' },
    // ── Community trusts — additional regional ─────────────────────────────
    { url: 'https://www.communitytrustsouth.nz/what-we-fund/', regions: ['southland', 'otago'] },
    { url: 'https://www.clt.net.nz/funding', regions: ['otago'] },                                      // Central Lakes Trust (Queenstown Lakes / Central Otago)
    { url: 'https://comtrust.org.nz', regions: ['canterbury'] },                                        // Community Trust Mid & South Canterbury
    { url: 'https://www.taranakielectricitytrust.co.nz/grants/', regions: ['taranaki'] },
    // ── Casino community trusts — regional ──────────────────────────────────
    { url: 'https://skycityauckland.co.nz/about-us/community-trust/how-to-apply/', regions: ['auckland', 'northland'] },
    { url: 'https://skycityhamilton.co.nz/about-us/community-trust/our-funding-grants/community-grant/', regions: ['waikato'] },
    { url: 'https://skycityqueenstown.co.nz/about-us/community-trust/', regions: ['otago'] },
    // ── Community trusts — regional ─────────────────────────────────────────
    { url: 'https://www.foundationnorth.org.nz/funding', regions: ['auckland', 'northland'] },
    { url: 'https://www.trustwaikato.co.nz/funding', regions: ['waikato'] },
    { url: 'https://www.baytrust.org.nz/apply-for-funding', regions: ['bay-of-plenty'] },
    { url: 'https://www.tect.org.nz/our-funds/', regions: ['bay-of-plenty'] },
    { url: 'https://ecct.org.nz/funding', regions: ['gisborne', 'hawkes-bay', 'manawatu-whanganui'] },
    { url: 'https://wct.org.nz/funding/', regions: ['wellington'] },
    { url: 'https://ratafoundation.org.nz/en/funding', regions: ['canterbury', 'west-coast', 'nelson', 'tasman', 'marlborough'] },
    { url: 'https://www.oct.org.nz/funding/apply-for-funding', regions: ['otago'] },
    { url: 'https://toifoundation.org.nz/how-we-fund/', regions: ['taranaki'] },
    { url: 'https://welenergytrust.co.nz/grants', regions: ['waikato'] },
    { url: 'https://www.centralenergytrust.org.nz/community-grants', regions: ['manawatu-whanganui'] },
    { url: 'https://www.trusthorizon.org.nz/funding', regions: ['bay-of-plenty'] },
    { url: 'https://trusthouse.org.nz/who-can-apply/', regions: ['wellington', 'manawatu-whanganui'] },
    { url: 'https://rotoruatrust.org.nz/grants/', regions: ['bay-of-plenty'] },
    // ── Community foundations — regional ─────────────────────────────────────
    { url: 'https://www.acornfoundation.org.nz/apply-funding/how-to-apply-for-funding', regions: ['bay-of-plenty'] },
    { url: 'https://www.nikaufoundation.nz/funding-hub', regions: ['wellington'] },
    { url: 'https://www.aucklandfoundation.org.nz/apply-for-grants', regions: ['auckland'] },
    { url: 'https://momentumwaikato.nz/how-we-fund', regions: ['waikato'] },
    { url: 'https://www.sunrisefoundation.org.nz/grants', regions: ['gisborne'] },
    { url: 'https://www.aorakifoundation.org.nz/apply-for-a-grant', regions: ['canterbury'] },  // Aoraki Foundation (community foundation, Timaru)
    { url: 'https://www.ebcf.nz/apply-for-funding/', regions: ['bay-of-plenty'] },
    { url: 'https://hawkesbayfoundation.org.nz/grant/how-to-apply-for-funding/', regions: ['hawkes-bay'] },
    { url: 'https://geysercf.org.nz/get/community-funding/', regions: ['bay-of-plenty', 'waikato'] },
    { url: 'https://www.whanganuicommunityfoundation.org.nz/page/apply/10/', regions: ['manawatu-whanganui'] },
    { url: 'https://www.topsouthfoundation.org.nz/our-grant-process/', regions: ['nelson', 'tasman', 'marlborough'] },
    { url: 'https://taranakifoundation.org.nz/apply-for-funding/', regions: ['taranaki'] },
    { url: 'https://www.northlandcommunityfoundation.org.nz/grants', regions: ['northland'] },
    { url: 'https://www.45south.org/funding', regions: ['otago'] },  // formerly Wakatipu Community Foundation
    { url: 'https://www.cluthafoundation.org.nz/apply/', regions: ['otago'] },
    { url: 'https://ttcfltd.org.nz/how-to-apply/', regions: ['auckland'] },
    // ── Charitable / philanthropic trusts — national ────────────────────────
    { url: 'https://www.toddfoundation.org.nz/who-we-fund/' },
    { url: 'https://tindall.org.nz/community/' },
    { url: 'https://www.jrmckenzie.org.nz/what' },
    { url: 'https://www.perpetualguardian.co.nz/philanthropy/grant-seekers/' },
    { url: 'https://www.perpetualguardian.co.nz/philanthropy/grant-seekers/grants-open-upcoming/' },
    { url: 'https://www.kct.co.nz/' },
    { url: 'https://sutherlandselfhelptrust.org.nz/grant-application/' },
    { url: 'https://milfordfoundation.co.nz/grants/' },
    { url: 'https://www.sargoodbequest.org.nz/' },
    { url: 'https://www.borrinfoundation.nz/grants/' },
    { url: 'https://fletchertrust.co.nz/applications.php' },
    { url: 'https://www.trustees.co.nz/charities/our-charitable-trusts/' },
    { url: 'https://freemasonsnz.org/charity/the-freemasons-charity-grants' },
    // ── Charitable trusts — regional ────────────────────────────────────────
    { url: 'https://www.bryanttrust.co.nz/funding', regions: ['waikato'] },
    { url: 'https://www.wfct.org.nz/', regions: ['canterbury'] },
    { url: 'https://www.publictrust.co.nz/grants/t-g-macarthy-trust/', regions: ['wellington'] },
    { url: 'https://www.publictrust.co.nz/grants/frozen-funds-charitable-trust/' },
    { url: 'https://www.publictrust.co.nz/grants/thomas-george-macarthy-trust/' },
    { url: 'https://www.publictrust.co.nz/grants/sir-john-logan-campbell-residuary-estate/' },
    { url: 'https://www.publictrust.co.nz/grants/charles-fleming-fund/' },
    { url: 'https://www.publictrust.co.nz/grants/john-ilott-charitable-trust/' },
    { url: 'https://www.publictrust.co.nz/grants/cossio-fyfe-trust/' },
    { url: 'https://www.publictrust.co.nz/grants/wellington-paraplegic-trust/' },
    { url: 'https://www.publictrust.co.nz/grants/sargood-bequest/' },
    { url: 'https://www.publictrust.co.nz/grants/norman-kirk-memorial-trust/' },
    { url: 'https://www.publictrust.co.nz/grants/john-feeney-memorial-trust/' },
    { url: 'https://www.healthcareotago.co.nz/charitable-trust', regions: ['otago'] },
    { url: 'https://www.ruralcommunitiestrust.org.nz/grants' },
    { url: 'https://wff.acumenonline.co.nz/Funding' },  // Wright Family Foundation
    // ── Discovered via directory scraping ──────────────────────────────────
    { url: 'http://www.nextfoundation.org.nz/applications' },           // NEXT Foundation (environmental/education)
    { url: 'http://www.tsbtrust.org.nz', regions: ['taranaki'] },       // TSB Community Trust
    { url: 'http://www.wccomtrust.org.nz', regions: ['west-coast'] },   // West Coast Community Trust
    { url: 'http://www.ctos.org.nz', regions: ['otago', 'southland'] }, // Community Trust of Southland
    { url: 'http://www.lenreynoldstrust.co.nz' },                       // Len Reynolds Trust
    { url: 'https://maorieducation.org.nz' },                           // NZ Maori Education Trust (via PG)
    { url: 'https://www.nzcat.org.nz' },                                // NZ Charities Aid Trust (via PG)
    { url: 'https://www.mbie.govt.nz/science-and-technology/science-and-innovation/funding-information-and-opportunities/investment-funds' },
    { url: 'https://www.mpi.govt.nz/funding-and-programmes/sustainable-food-and-fibre-futures/about-sustainable-food-and-fibre-futures' },
    { url: 'https://www.savethekiwi.nz/about-us/what-we-do/funding' },  // Save the Kiwi Trust
    { url: 'https://predatorfreenz.org/toolkits/groups-toolkit/funding-and-grants' },
    { url: 'https://qeiinationaltrust.org.nz/managing-your-covenant/the-stephenson-fund' },
    { url: 'https://www.aucklandzoo.co.nz/get-involved/conservation-fund', regions: ['auckland'] },
    { url: 'https://trail-fund.myshopify.com/pages/apply-for-a-grant' }, // NZ Trail Fund
    { url: 'http://www.herengaanuku.govt.nz/enhanced-access-fund' },     // Heritage Trails NZ
    // ── Health / research trusts — national ─────────────────────────────────
    { url: 'https://www.paykeltrust.co.nz/project-equipment-grants/' },
    { url: 'https://www.cancerresearchtrustnz.org.nz/apply-for-a-grant' },
    { url: 'https://www.tewhatuora.govt.nz/for-the-health-sector/information-for-pacific-communities/pacific-community-health-fund' },
    { url: 'https://grants.curekids.org.nz/' },
    // ── Environment / conservation — national ───────────────────────────────
    { url: 'https://wwf.org.nz/community-conservation-and-education-fund' },
    { url: 'https://www.airnewzealand.co.nz/sustainability-every-corner-project' },
    // ── Arts / culture / education — regional ───────────────────────────────
    { url: 'https://www.earletrust.org.nz/how-to-apply', regions: ['manawatu-whanganui'] },
    { url: 'https://marlborough.inspirefoundation.co.nz/grants', regions: ['marlborough'] },
    // ── Iwi / Maori trusts — regional ───────────────────────────────────────
    { url: 'https://ngaitahu.iwi.nz/opportunities-and-resources/for-whanau/find-an-opportunity/ngai-tahu-fund/', regions: ['canterbury', 'otago', 'southland', 'west-coast'] },
    { url: 'https://waikatotainui.com/grants/', regions: ['waikato'] },
    { url: 'https://www.tst.maori.nz/grants/', regions: ['waikato', 'bay-of-plenty'] },
    // ── Corporate foundations & CSR — national ──────────────────────────────
    { url: 'https://www.anz.co.nz/about-us/corporate-responsibility/community/staff-foundation/' },
    { url: 'https://terourou.one.nz/' },
    { url: 'https://www.spark.co.nz/online/about/sustainability/spark-foundation/funding' },
    { url: 'https://www.bnz.co.nz/about-us/sustainability/bnz-foundation/manaaki-tangata-grant' },
    { url: 'https://www.transpower.co.nz/communitycare-fund' },
    { url: 'https://pulseenergy.co.nz/powering-your-community-fund/' },
    { url: 'https://www.z.co.nz/about-z/what-we-stand-for/community/good-in-the-hood/application-terms-and-conditions' },
    { url: 'https://www.harcourtsfoundation.org/new-zealand' },
    { url: 'https://www.woolworths.co.nz/info/community-and-environment/growing-for-good-grants' },
    { url: 'https://www.fonterra.com/nz/en/sustainability/people/caring-for-communities.html' },
    { url: 'https://www.beeflambnz.co.nz/community-fund' },
    { url: 'https://agmardt.org.nz/our-funding-programmes/' },
    { url: 'https://foundation.asb.co.nz/apply' },  // ASB Foundation (corporate foundation, distinct from Foundation North)
    { url: 'https://www.kiwibank.co.nz/about-us/community/local-hero/' },
    { url: 'https://www.westpac.co.nz/about-us/sustainability-community/community/community-grants/' },
    { url: 'https://www.2degrees.nz/community' },
    { url: 'https://www.genesisenergy.co.nz/community/community-fund' },
    { url: 'https://contact.co.nz/about-contact/community-fund' },
    { url: 'https://www.vector.co.nz/about-us/community' },
    { url: 'https://www.thewarehouse.co.nz/red-shirts-in-the-community' },
    { url: 'https://www.fletcherbuilding.com/sustainability/community' },
    { url: 'https://www.portoftauranga.com/sustainability/community/', regions: ['bay-of-plenty'] },
    { url: 'https://www.centreport.co.nz/about-us/community/', regions: ['wellington'] },
    { url: 'https://www.dairynz.co.nz/about-us/community/' },
    // ── Corporate — regional ────────────────────────────────────────────────
    { url: 'https://www.meridianenergy.co.nz/community-support/fund', regions: ['otago', 'southland', 'canterbury', 'wellington', 'manawatu-whanganui'] },
    { url: 'https://www.mercury.co.nz/about-us/partnerships/community-funds', regions: ['waikato', 'bay-of-plenty', 'canterbury'] },
    { url: 'https://www.powerco.co.nz/what-we-do/community-partnerships/powerco-community-fund', regions: ['taranaki', 'waikato', 'bay-of-plenty', 'manawatu-whanganui', 'wellington'] },
    { url: 'https://www.foodstuffs-si.co.nz/foodstuffs-community-trust', regions: ['canterbury', 'otago', 'southland', 'west-coast', 'nelson', 'tasman', 'marlborough'] },
    // ── City councils ───────────────────────────────────────────────────────
    { url: 'https://www.aucklandcouncil.govt.nz/grants-community-support-housing/grants/Pages/default.aspx', regions: ['auckland'] },
    { url: 'https://wellington.govt.nz/community-support-and-resources/community-support/funding', regions: ['wellington'] },
    { url: 'https://ccc.govt.nz/culture-and-community/community-funding', regions: ['canterbury'] },
    { url: 'https://hamilton.govt.nz/community-support-and-funding/funding', regions: ['waikato'] },
    { url: 'https://www.dunedin.govt.nz/services/funding-and-grants', regions: ['otago'] },
    { url: 'https://www.tauranga.govt.nz/culture-and-community/grants-and-funding', regions: ['bay-of-plenty'] },
    { url: 'https://www.pncc.govt.nz/Community/Community-funding', regions: ['manawatu-whanganui'] },
    { url: 'https://www.nelson.govt.nz/services/community/funding/', regions: ['nelson'] },
    { url: 'https://www.icc.govt.nz/community/funding-awards-and-grants/', regions: ['southland'] },
    { url: 'https://www.napier.govt.nz/napier/grants/', regions: ['hawkes-bay'] },
    { url: 'https://poriruacity.govt.nz/services/community-support/', regions: ['wellington'] },
    { url: 'https://www.upperhutt.govt.nz/Community/Grants-and-funding', regions: ['wellington'] },
    { url: 'https://www.huttcity.govt.nz/people-and-communities/community-funding', regions: ['wellington'] },
    // ── District councils — Northland ────────────────────────────────────────
    { url: 'https://www.fndc.govt.nz/Your-district/Funding', regions: ['northland'] },
    { url: 'https://www.wdc.govt.nz/Community/Community-funding', regions: ['northland'] },
    { url: 'https://www.kaipara.govt.nz/funding', regions: ['northland'] },
    // ── District councils — Waikato ─────────────────────────────────────────
    { url: 'https://www.tcdc.govt.nz/Our-Community/Funding-Sponsorship-and-Grants', regions: ['waikato'] },
    { url: 'https://www.hauraki-dc.govt.nz/community/grants-funding', regions: ['waikato'] },
    { url: 'https://www.waikatodistrict.govt.nz/services-facilities/community-development/funding', regions: ['waikato'] },
    { url: 'https://www.mpdc.govt.nz/grants-and-funding', regions: ['waikato'] },
    { url: 'https://www.waipadc.govt.nz/our-services/grants-and-funding', regions: ['waikato'] },
    { url: 'https://www.otodc.govt.nz/our-district/funding-and-grants', regions: ['waikato'] },
    { url: 'https://www.southwaikato.govt.nz/our-council/grants-and-funding', regions: ['waikato'] },
    { url: 'https://www.waitomo.govt.nz/council/funding-and-grants', regions: ['waikato'] },
    { url: 'https://www.taupodc.govt.nz/community/community-grants-and-awards', regions: ['waikato'] },
    // ── District councils — Bay of Plenty ───────────────────────────────────
    { url: 'https://www.westernbay.govt.nz/community/grants-and-funding', regions: ['bay-of-plenty'] },
    { url: 'https://www.rotorualakescouncil.nz/community/grants-and-funding', regions: ['bay-of-plenty'] },
    { url: 'https://www.whakatane.govt.nz/community-grants', regions: ['bay-of-plenty'] },
    { url: 'https://www.kaweraudc.govt.nz/about-the-council/community-grants', regions: ['bay-of-plenty'] },
    { url: 'https://www.odc.govt.nz/our-district/community-grants', regions: ['bay-of-plenty'] },
    // ── District councils — Gisborne ────────────────────────────────────────
    { url: 'https://www.gdc.govt.nz/council/funding-streams', regions: ['gisborne'] },
    // ── District councils — Hawke's Bay ─────────────────────────────────────
    { url: 'https://www.wairoadc.govt.nz/our-district/grants-funding/mayoral-grants/', regions: ['hawkes-bay'] },
    { url: 'https://www.hastingsdc.govt.nz/hastings/grants/', regions: ['hawkes-bay'] },
    { url: 'https://www.chbdc.govt.nz/our-district/community-development/grants/', regions: ['hawkes-bay'] },
    // ── District councils — Taranaki ────────────────────────────────────────
    { url: 'https://www.npdc.govt.nz/community/community-partnerships/funding-and-grants/', regions: ['taranaki'] },
    { url: 'https://www.stratford.govt.nz/our-district/funding-and-grants', regions: ['taranaki'] },
    { url: 'https://www.southtaranaki.com/our-community/funding-and-grants', regions: ['taranaki'] },
    // ── District councils — Manawatu-Whanganui ──────────────────────────────
    { url: 'https://www.ruapehudc.govt.nz/our-district/grants', regions: ['manawatu-whanganui'] },
    { url: 'https://www.whanganui.govt.nz/Community-and-Places/Funding-Opportunities', regions: ['manawatu-whanganui'] },
    { url: 'https://www.rangitikei.govt.nz/district/community/grants-funding', regions: ['manawatu-whanganui'] },
    { url: 'https://www.mdc.govt.nz/about-council/community-funding', regions: ['manawatu-whanganui'] },
    { url: 'https://www.tararuadc.govt.nz/living-here/community-information/community-funding', regions: ['manawatu-whanganui'] },
    { url: 'https://www.horowhenua.govt.nz/CommunityPlaces/Grants-Community-Funding', regions: ['manawatu-whanganui'] },
    // ── District councils — Wellington ───────────────────────────────────────
    { url: 'https://www.kapiticoast.govt.nz/services/grants-and-funding/', regions: ['wellington'] },
    { url: 'https://www.mstn.govt.nz/community/community-grants', regions: ['wellington'] },
    { url: 'https://cdc.govt.nz/your-district/community/funding/', regions: ['wellington'] },
    { url: 'https://swdc.govt.nz/community/grants/', regions: ['wellington'] },
    // ── District councils — Top of South ────────────────────────────────────
    { url: 'https://www.marlborough.govt.nz/our-community/grants-and-awards', regions: ['marlborough'] },
    { url: 'https://www.tasman.govt.nz/my-community/grants-and-funding', regions: ['tasman'] },
    // ── District councils — Canterbury ───────────────────────────────────────
    { url: 'https://www.kaikoura.govt.nz/our-services/community-grants-services-and-development/community-grants/', regions: ['canterbury'] },
    { url: 'https://www.hurunui.govt.nz/community/awards-and-funding', regions: ['canterbury'] },
    { url: 'https://www.waimakariri.govt.nz/council/funding-and-grants', regions: ['canterbury'] },
    { url: 'https://www.selwyn.govt.nz/services/funding-And-grants', regions: ['canterbury'] },
    { url: 'https://www.ashburtondc.govt.nz/ashburton-district/grants-and-funding', regions: ['canterbury'] },
    { url: 'https://www.timaru.govt.nz/community/community-and-culture/community-funding', regions: ['canterbury'] },
    { url: 'https://www.mackenzie.govt.nz/community/grants-and-scholarships', regions: ['canterbury'] },
    { url: 'https://www.waimatedc.govt.nz/community/grants', regions: ['canterbury'] },
    // ── District councils — Otago ───────────────────────────────────────────
    { url: 'https://www.waitaki.govt.nz/About-Waitaki/Living-here/Supporting-our-community/Community-Grants-and-Awards', regions: ['otago'] },
    { url: 'https://www.codc.govt.nz/services/funding-grants', regions: ['otago'] },
    { url: 'https://www.qldc.govt.nz/community/community-funding/', regions: ['otago'] },
    { url: 'https://www.cluthadc.govt.nz/community/grants-and-funding', regions: ['otago'] },
    // ── District councils — Southland ───────────────────────────────────────
    { url: 'https://www.southlanddc.govt.nz/council/funding-and-grants/', regions: ['southland'] },
    { url: 'https://www.goredc.govt.nz/council/grants-funding', regions: ['southland'] },
    // ── District councils — West Coast ──────────────────────────────────────
    { url: 'https://www.westlanddc.govt.nz/community-support-and-resources/community-grants/', regions: ['west-coast'] },
    { url: 'https://www.greydc.govt.nz/03your-community/grants-and-funding', regions: ['west-coast'] },
    { url: 'https://bullerdc.govt.nz/your-council/community-funding/', regions: ['west-coast'] },
    // ── Regional councils ───────────────────────────────────────────────────
    { url: 'https://www.nrc.govt.nz/environment/funding-and-awards/', regions: ['northland'] },
    { url: 'https://www.waikatoregion.govt.nz/community/funding-and-scholarships/', regions: ['waikato'] },
    { url: 'https://www.boprc.govt.nz/living-in-the-bay/community-funding/', regions: ['bay-of-plenty'] },
    { url: 'https://www.hbrc.govt.nz/hawkes-bay/community/', regions: ['hawkes-bay'] },
    { url: 'https://www.horizons.govt.nz/about-our-region-and-council/grants-and-sponsorship', regions: ['manawatu-whanganui'] },
    { url: 'https://www.gw.govt.nz/your-region/funding-and-awards/', regions: ['wellington'] },
    { url: 'https://www.ecan.govt.nz/get-involved/community-funding', regions: ['canterbury'] },
    { url: 'https://www.orc.govt.nz/environment/enhancing-and-protecting/grants-and-funding/', regions: ['otago'] },
    { url: 'https://www.trc.govt.nz/environment/working-together/landowner-funding-assistance', regions: ['taranaki'] },
    { url: 'https://www.wcrc.govt.nz/community/funding', regions: ['west-coast'] },
    { url: 'https://www.es.govt.nz/community/funding-and-grants', regions: ['southland'] },
    // ── Sports — regional ───────────────────────────────────────────────────
    { url: 'https://www.oxfordsportstrust.org.nz/grants.htm', regions: ['northland'] },
  ],

  seedQueryTemplates: [
    '{country} grants apply "{purpose}" non-profit {year}',
    '{country} community charitable trust grants {year} apply',
    '{country} local council community grants apply {year}',
    'site:communitymatters.govt.nz lottery grants apply',
    '{country} corporate foundation community grants apply {year}',
    '{country} government grants not-for-profit {year}',
    'NZ gaming trust grants apply {year}',
    'pokie trust grants {country} community apply {year}',
  ],

  excludedDomains: [
    'nzherald.co.nz', 'stuff.co.nz', 'rnz.co.nz', 'scoop.co.nz',
    'newshub.co.nz', 'tvnz.co.nz', 'beehive.govt.nz',
    'charities.govt.nz', 'grantguru.co.nz',
    'givealittle.co.nz', 'gofundme.com',
    'wikipedia.org', 'wikimedia.org', 'linkedin.com', 'facebook.com',
    'twitter.com', 'instagram.com', 'youtube.com', 'reddit.com',
  ],

  regions: [
    { id: 'northland', name: 'Northland' },
    { id: 'auckland', name: 'Auckland' },
    { id: 'waikato', name: 'Waikato' },
    { id: 'bay-of-plenty', name: 'Bay of Plenty' },
    { id: 'gisborne', name: 'Gisborne' },
    { id: 'hawkes-bay', name: "Hawke's Bay" },
    { id: 'taranaki', name: 'Taranaki' },
    { id: 'manawatu-whanganui', name: 'Manawatū-Whanganui' },
    { id: 'wellington', name: 'Wellington' },
    { id: 'tasman', name: 'Tasman' },
    { id: 'nelson', name: 'Nelson' },
    { id: 'marlborough', name: 'Marlborough' },
    { id: 'west-coast', name: 'West Coast' },
    { id: 'canterbury', name: 'Canterbury' },
    { id: 'otago', name: 'Otago' },
    { id: 'southland', name: 'Southland' },
    { id: 'chatham-islands', name: 'Chatham Islands' },
  ],
};
